export const ADD_EXERCISE = 'ADD_EXERCISE';
export const UPDATE_EXERCISE = 'UPDATE_EXERCISE';
export const DELETE_EXERCISE = 'DELETE_EXERCISE';

export const SET_SELECTED_EXERCISE = 'SET_SELECTED_EXERCISE';
export const REMOVE_SELECTED_EXERCISE = 'REMOVE_SELECTED_EXERCISE';
export const SET_EDIT_MODE = 'SET_EDIT_MODE';
